import { useState, useEffect } from 'react';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../lib/firebase';
import type { CrossGenreInsightDoc } from '../types';

/**
 * Reads the single cross-genre insight doc for the given granularity
 * (crossGenreInsights/{granularity}), regenerated by the "Re-analyze" flow.
 * `refreshKey` lets the page force a re-read after generation completes.
 */
export function useCrossGenreInsights(
  granularity: 'month' | 'week' = 'month',
  refreshKey = 0
) {
  const [insight, setInsight] = useState<CrossGenreInsightDoc | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);

    (async () => {
      try {
        const snap = await getDoc(doc(db, 'crossGenreInsights', granularity));
        if (cancelled) return;
        if (snap.exists()) {
          const data = snap.data();
          setInsight({
            granularity,
            generatedAt: data.generatedAt?.toDate() || new Date(),
            genresAnalyzed: data.genresAnalyzed || [],
            repeatedConcepts: data.repeatedConcepts || [],
            analysis: data.analysis || '',
            newGameIdeas: data.newGameIdeas || [],
          });
        } else {
          setInsight(null);
        }
      } catch {
        if (!cancelled) setInsight(null);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => { cancelled = true; };
  }, [granularity, refreshKey]);

  return { insight, loading };
}
